# Use uma imagem base do Node.js
FROM node:14

# Instale as dependências, incluindo o 'canvas'
RUN apt-get update && apt-get install -y \
    build-essential \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Comando de inicialização da aplicação
CMD ["npm", "start"]
